/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FdcAccountingTrustless {
  export type RequestBodyStruct = {
    transactionHash: BytesLike;
    requiredConfirmations: BigNumberish;
    provideInput: boolean;
    listEvents: boolean;
    logIndices: BigNumberish[];
  };

  export type RequestBodyStructOutput = [
    transactionHash: string,
    requiredConfirmations: bigint,
    provideInput: boolean,
    listEvents: boolean,
    logIndices: bigint[]
  ] & {
    transactionHash: string;
    requiredConfirmations: bigint;
    provideInput: boolean;
    listEvents: boolean;
    logIndices: bigint[];
  };

  export type EventStruct = {
    logIndex: BigNumberish;
    emitterAddress: AddressLike;
    topics: BytesLike[];
    data: BytesLike;
    removed: boolean;
  };

  export type EventStructOutput = [
    logIndex: bigint,
    emitterAddress: string,
    topics: string[],
    data: string,
    removed: boolean
  ] & {
    logIndex: bigint;
    emitterAddress: string;
    topics: string[];
    data: string;
    removed: boolean;
  };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    timestamp: BigNumberish;
    sourceAddress: AddressLike;
    isDeployment: boolean;
    receivingAddress: AddressLike;
    value: BigNumberish;
    input: BytesLike;
    status: BigNumberish;
    events: FdcAccountingTrustless.EventStruct[];
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    timestamp: bigint,
    sourceAddress: string,
    isDeployment: boolean,
    receivingAddress: string,
    value: bigint,
    input: string,
    status: bigint,
    events: FdcAccountingTrustless.EventStructOutput[]
  ] & {
    blockNumber: bigint;
    timestamp: bigint;
    sourceAddress: string;
    isDeployment: boolean;
    receivingAddress: string;
    value: bigint;
    input: string;
    status: bigint;
    events: FdcAccountingTrustless.EventStructOutput[];
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: FdcAccountingTrustless.RequestBodyStruct;
    responseBody: FdcAccountingTrustless.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: FdcAccountingTrustless.RequestBodyStructOutput,
    responseBody: FdcAccountingTrustless.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: FdcAccountingTrustless.RequestBodyStructOutput;
    responseBody: FdcAccountingTrustless.ResponseBodyStructOutput;
  };
}

export interface FdcAccountingTrustlessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositAddress"
      | "getBalance"
      | "processed"
      | "rootRelayer"
      | "roots"
      | "syncRoot"
      | "verifyAndCredit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DepositCredited" | "RootSynced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rootRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roots", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "syncRoot",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndCredit",
    values: [BytesLike[], FdcAccountingTrustless.ResponseStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "processed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rootRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "syncRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndCredit",
    data: BytesLike
  ): Result;
}

export namespace DepositCreditedEvent {
  export type InputTuple = [
    sourceAddress: AddressLike,
    value: BigNumberish,
    txHash: BytesLike
  ];
  export type OutputTuple = [
    sourceAddress: string,
    value: bigint,
    txHash: string
  ];
  export interface OutputObject {
    sourceAddress: string;
    value: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RootSyncedEvent {
  export type InputTuple = [votingRound: BigNumberish, merkleRoot: BytesLike];
  export type OutputTuple = [votingRound: bigint, merkleRoot: string];
  export interface OutputObject {
    votingRound: bigint;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FdcAccountingTrustless extends BaseContract {
  connect(runner?: ContractRunner | null): FdcAccountingTrustless;
  waitForDeployment(): Promise<this>;

  interface: FdcAccountingTrustlessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositAddress: TypedContractMethod<[], [string], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  processed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  rootRelayer: TypedContractMethod<[], [string], "view">;

  roots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  syncRoot: TypedContractMethod<
    [votingRound: BigNumberish, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyAndCredit: TypedContractMethod<
    [merkleProof: BytesLike[], response: FdcAccountingTrustless.ResponseStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "processed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "rootRelayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "syncRoot"
  ): TypedContractMethod<
    [votingRound: BigNumberish, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndCredit"
  ): TypedContractMethod<
    [merkleProof: BytesLike[], response: FdcAccountingTrustless.ResponseStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DepositCredited"
  ): TypedContractEvent<
    DepositCreditedEvent.InputTuple,
    DepositCreditedEvent.OutputTuple,
    DepositCreditedEvent.OutputObject
  >;
  getEvent(
    key: "RootSynced"
  ): TypedContractEvent<
    RootSyncedEvent.InputTuple,
    RootSyncedEvent.OutputTuple,
    RootSyncedEvent.OutputObject
  >;

  filters: {
    "DepositCredited(address,uint256,bytes32)": TypedContractEvent<
      DepositCreditedEvent.InputTuple,
      DepositCreditedEvent.OutputTuple,
      DepositCreditedEvent.OutputObject
    >;
    DepositCredited: TypedContractEvent<
      DepositCreditedEvent.InputTuple,
      DepositCreditedEvent.OutputTuple,
      DepositCreditedEvent.OutputObject
    >;

    "RootSynced(uint64,bytes32)": TypedContractEvent<
      RootSyncedEvent.InputTuple,
      RootSyncedEvent.OutputTuple,
      RootSyncedEvent.OutputObject
    >;
    RootSynced: TypedContractEvent<
      RootSyncedEvent.InputTuple,
      RootSyncedEvent.OutputTuple,
      RootSyncedEvent.OutputObject
    >;
  };
}
